site_name: Anleitung
nav:
  #- Home: index.md
  #- Kleiner Blindtext: blindtext.md
  #- Wortberge: wortberge.md
theme:
  #name: readthedocs
  name: null 
  #custom_dir: 'minimal-theme/'
  custom_dir: 'myreadthedocs/'
  titles_only: false
  prev_next_buttons_location: none

  # Config options for 'readthedocs' theme

  static_templates:
      - 404.html

  include_search_page: true
  search_index_only: false

  highlightjs: true
  hljs_languages: []

  include_homepage_in_sidebar: true
  #prev_next_buttons_location: bottom
  navigation_depth: 4
  #titles_only: false
  sticky_navigation: true
  collapse_navigation: true

extra_css:
  - extra.css
use_directory_urls: false
#false ist mit .html dateien und funktioniert dann auch offline
plugins:
  - search:
      lang: de
      min_search_length: 2
      #minimum an characters für die suche
dev_addr: '0.0.0.0:8080'

